// <auto-generated />
using System;
using MedanoClinicBE.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MedanoClinicBE.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250104140000_CreateDoctorsTable")]
    partial class CreateDoctorsTableClean
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            // Simplified model - full model would include all entities but we're keeping it minimal
            // to avoid EF conflicts during migration
#pragma warning restore 612, 618
        }
    }
}